---
title: "Получение сведений о системе"
author: rudzsan@gmail.com
format: 
    md:
        output-file: README.md
engine: knitr
---


## Цель работы

Получить сведения об используемой системе

## Исходные данные

1. Ноутбук ASUS UX325JA

2. ОС Windows 11 Домашняя (Ubuntu 22.04.1 LTS (GNU/Linux 5.15.90.1-microsoft-standard-WSL2 x86_64))

3. Интерпретатор командной оболочки bash

## План

1. Ввод команд в эмулятор терминала

2. Анализ данных

## Ход работы

1. Получение сведений об используемом дистрибутиве:

```{bash}
lsb_release -a
```

В результате, используемый дистрибутив был определен как - Ubuntu 22.04.1 LTS.

2. Получение сведений о версии ядра:

```{bash}
uname -a
```

После выполнения команды, стали известны версия ядра - 5.15.90.1, дата компиляции ядра - 27 января 2023 года.

3. Получение сведений о процессоре:

```{bash}
cat /proc/cpuinfo | grep "model name"
```

Было определено, что используемый процессор - восьмипоточный Intel Core i5-1035G1 с тактовой частотой 1.0 ГГц.

4. Получение последних 30 строк логов системы:

```{bash}
dmesg | tail -n 30
```

## Оценка результата

По итогам всех выполненных операций в лабораторной работе №1 была получена базовая информация об используемой системе.

## Вывод

Таким образом, с помощью команд Linux, научился получать сведения о системе.
