---
title: "Применение средств и методов OSINT"
author: Рудзик А.Р.
format: 
    md:
        output-file: README.md
engine: knitr
---

## Цель работы

1. Освоить базовые подходы процессов OSINT

2. Освоить современные инструменты поиска и сбора информации

3. Освоить инструменты совместной работы в ходе аналитической деятельности

## План выполнения

1. Собрать информацию о профильных компаниях в сфере ИБ и их продуктах.

2. Собрать информацию об основных специализированных технологиях, применяемых в средствах защиты информации.

3. Собрать информацию о публичных сотрудниках, ведущих профильные технологические блоги, профили в социальных сетях и т.д.

4. Сформировать представление о рынке отечественных решений ИБ.

## Ход выполнения практической работы

Номер по списку - 9. Компания Positive Technologies

### Основная информация о компании

Полное название компании: Акционерное общество «Позитив Текнолоджиз»

Юридический адрес: 107241, г. Москва, Щелковское шоссе, д. 23А, помещение V, комната 30

ИНН: 7718668887

ОГРН: 1077761087117

Компания входит в реестр аккредитованных ИТ-компаний

### Контактные номера телефонов

Телефон:

+7 (495) 744-01-44

+7 495 540 53 28

8 800 234 01 44

Факс:

+7 (495) 744-01-87

### Адреса электронной почты

pt@ptsecurity.com

info@ptsecurity.com

info-group@ptsecurity.com

shareholder@ptsecurity.com

### Структура компании

Денис Сергеевич Баранов - генеральный директор PT

Денис  Кораблев - управляющий директор PT

Артем Сычев - Советник генерального директора PT

Борис Борисович Симис - Заместитель генерального директора PT по развитию бизнеса

Алексей Вячеславович Андреев - Управляющий директор PT

Максим Филиппов - Заместитель генерального директора PT

Денис Кораблев - Управляющий директор, директор по продуктам PT

[источник](https://www.ptsecurity.com/ru-ru/about/speakers/)

#### Офис в Москве

 - Преображенская площадь, д.8, 107061

#### Офис в Санкт-Петербурге

 - Ул. Итальянская д. 17, 191186

#### Офис в Нижнем Новгороде

 - Ул. Тимирязева, дом 15, корп. 2, этаж 2, 603022

#### Офис в Новосибирске

 - Вокзальная магистраль, д. 1/1, БЦ «Лига Капитал», офис 706, 630004
 - Ул. Николаева, д. 13, 630090

#### Офис в Самаре

 - Ул. Молодогвардейская, д. 204, офисы 602 и 603, 443001

#### Офис в Томске

 - Пр. Фрунзе, д. 103, БЦ «Красное знамя», этаж 5, 634021

[источник](https://www.ptsecurity.com/ru-ru/about/contacts/)

### Основные направления деятельности компании

#### Виды деятельности согласно общероссийскому классификатору видов экономической деятельности:

 - 62.0 (основной) - Разработка компьютерного программного обеспечения, консультационные услуги в данной области и другие сопутствующие услуги
 - 62.02 - Деятельность консультативная и работы в области компьютерных технологий
 - 62.02.1 - Деятельность по планированию, проектированию компьютерных систем
 - 62.02.4 - Деятельность по подготовке компьютерных систем к эксплуатации
 - 62.03.13 - Деятельность по сопровождению компьютерных систем
 - 62.09 - Деятельность, связанная с использованием вычислительной техники и информационных технологий, прочая
 - 63.11.1 - Деятельность по созданию и использованию баз данных и информационных ресурсов
 - 73.1 - Деятельность рекламная
 - 74.90.9 - Деятельность в области защиты информации

### Производимые продукты, основные сферы их применения, их достоинства

MaxPatrol VM -  система, позволяющая выстроить процесс управления уязвимостями и контролировать защищенность IT-инфраструктуры компании в любой момент.

MaxPatrol SIEM - система мониторинга событий информационной безопасности.
Постоянно пополняется знаниями экспертов о способах детектирования
актуальных угроз и адаптируется к изменениям в защищаемой сети. В 2020 году
количество продаж MaxPatrol SIEM выросло на 85%.

PT Sandbox -  песочница, позволяющая защитить инфраструктуру компании от целевых и массовых атак с применением вредоносного ПО и уязвимостей нулевого дня.

MaxPatrol 8 - система предназначена для обеспечения контроля защищенности и соответствия стандартам безопасности информационных систем.

MaxPatrol O2 - метапродукт, который позволяет обнаруживать и останавливать атаки злоумышленников в автоматическом режиме с измеримым эффектом силами одного человека. Решает проблему серьезного дефицита квалифицированных кадров в индустрии и помогает защитить организации по всему миру.

PT ISIM -  система анализа трафика сетей АСУ ТП. Позволяет находить следы нарушений информационной безопасности в технологических сетях, помогает на ранней стадии выявлять кибератаки, активность вредоносного ПО, неавторизованные действия персонала (в том числе злоумышленные) и обеспечивает соответствие требованиям законодательства.

MaxPatrol SIEM All-in-One - система дает полную видимость IT-инфраструктуры малого и среднего масштаба и выявляет инциденты ИБ. Продукт позволяет получить полноценную работающую SIEM-систему при меньшем бюджете.

PT MultiScanner -  система защиты от вредоносных программ. Она выявляет вирусные угрозы, блокирует их распространение в инфраструктуре и обнаруживает скрытое присутствие зловредов, используя оптимальный набор антивирусов и уникальные правила PT Expert Security Center.

PT Network Attack Discovery - система глубокого анализа сетевого трафика (Network Traffic Analysis, NTA) для выявления атак на периметре и внутри сети.

PT AF - инновационная система защиты, которая точно обнаруживает и блокирует атаки, включая атаки из списка OWASP Top 10 и классификации WASC, L7 DDoS и атаки нулевого дня.

PT Application Inspector - продукт сочетает четыре технологии: статический (SAST) с уникальной технологией абстрактной интерпретации, интерактивный (IAST), анализ сторонних компонентов (SCA), а также динамический анализ (DAST).

Pt Platform 187 -  программно-аппаратный комплекс для реализации основных функций безопасности значимых объектов КИИ и взаимодействия с главным центром ГосСОПКА. Платформа включает в себя набор технических средств, который помогает выполнить основные требования законодательства.

PT Threat Intelligence Feeds - потоки данных (фиды) с индикаторами компрометации, предназначенные для информирования SOC-команд об актуальных угрозах ИБ. В основе наших фидов — данные об угрозах, аккумулированные экспертами PT ESC в ходе расследований инцидентов и изучения деятельности хакерских группировок во всем мире, а также данные обезличенной телеметрии, полученные с инсталляций наших продуктов в сотнях компаний.

Xspider - профессиональный сканер уязвимостей, позволяющий оценить реальное состояние защищенности IT-инфраструктуры. Решение быстро и точно определяет компоненты сети, сканирует сетевые ресурсы на наличие уязвимостей и выдает рекомендации по их устранению.

PT BlackBox - сканер безопасности приложений, работающий методом черного ящика. Дает рекомендации по устранению проблем. Упрощает работу специалистов R&D. Технология, которая позволяет использовать данные других продуктов Positive Technologies. База знаний основана на результатах исследований и опыте экспертов, создавалась более пяти лет и продолжает развиваться.

### Используемые технологии

Стек технологий: .NET (C#) Framework/Core, PostgreSQL, RabbitMQ, ELK, Event-Sourcing, Docker, Windows/Linux, Gitlab. [источник](https://www.ptsecurity.com/ru-ru/about/vacancy/351171/)

Основной стек технологий и языков у нас – ASP.NET Core, C++17, Python, Golang, PostgreSQL, Suricata, ClickHouse, Apache. [источник](https://hh.ru/employer/26624?hhtmFrom=vacancy_search_list)

### Основные клиенты и мероприятия компании

#### Обеспечение кибербезопасности мероприятий:

2013 г. — Всемирная летняя универсиада в Казани;

2014 г. — Олимпиада в Сочи;

2018 г. — чемпионат мира по футболу;

2018 г. — выборы президента России;

2019 г. — Всемирная зимняя универсиада в Красноярске;

2020 г. — голосование по поправкам к конституции;

2021 г. — выборы в Госдуму.

#### Проводит собственный научно-практический форум Positive Hack Days — крупнейшее мероприятие в области информационной безопасности в России и СНГ

#### Клиенты:

ПАО "Транснефть"

Роснефть

Мегафон

ОАО РЖД

АО Альфа-банк

Правительство Москвы и Московской области

АО «Концерн "Росэнергоатом"»

ПАО «Россети»

ПАО «ФСК ЕЭС»

ПАО «РусГидро»

Банк ВТБ (ПАО)

Центральный банк РФ

Ростех

### Основные веб-сайты компании и ее продуктов

[ptsecurity.com](https://www.ptsecurity.com)

Домены на IP 178.248.238.30:

 - ptsecurity.com
 - maxpatrol.com
 - maxpatrol.ru
 - phdays.ru

### Публичные сотрудники компании

#### Positive Hack Days 2023

 - Денис Баранов - Открытие мероприятия
 - Артем Проничев и Николай Лыфенко рассказали, как в Positive Technologies внедряют ML.
 - Владимир Кочетков - Открытие трека. Вступительное слово организаторов
 - Юрий Васин - Бесплатная криптография на микроконтроллерах за два бакса
 - Дмитрий Скляров - Я реверсер, я так вижу!
 - Константин Полишин - Социальная инженерия: тенденции red team, технические аспекты kill chain и проектный опыт
 - Владимир Кочетков, Сергей Подкорытов - Язык запросов к коду... не нужен?
 - Евгений Орлов - Кто живет в АСУ ТП и как его найти 
 - Георгий Александрия - Как разработчики анализатора исходного кода с одной экспонентой боролись
 - Артем Проничев, Николай Лыфенко - Как внедряем ML в Positive Technologies

### Социальные сети

[Группа ВКонтакте](https://vk.com/ptsecurity)

[Канал Телеграмм](https://telegram.me/s/Positive_Technologies)

[Канал Телеграмм](https://telegram.me/s/positive_investing)

[YouTube](https://www.youtube.com/@positivepressclub3719)

[Страница на Хабр](https://habr.com/ru/companies/pt/articles/)


## Вывод

В ходе выполнения практической работы была найдена информация о компании Positive Technologies с помощью процесса OSINT
